version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd frontend && npm install
      - cd ../backend && npm install
      
  build:
    commands:
      - echo Building frontend...
      - cd ../frontend
      - npm run build
      - echo Building backend...
      - cd ../backend
      - echo Backend build complete
      
  post_build:
    commands:
      - echo Deploying frontend to S3...
      - aws s3 sync frontend/out s3://my-nextjs-frontend --delete
      - echo Frontend deployed successfully
      - echo Preparing backend for deployment...

artifacts:
  files:
    - '**/*'
  base-directory: backend
